# Generated by Django 5.2.7 on 2025-11-20 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickconnect', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['sort_order', 'name'], 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='professional',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='session',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='category',
            name='avg_response_time',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='category',
            name='color',
            field=models.CharField(default='#6B7280', max_length=7),
        ),
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='category',
            name='sort_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='notification',
            name='action_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='notification',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10),
        ),
        migrations.AddField(
            model_name='professional',
            name='avg_response_time',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='professional',
            name='certifications',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='professional',
            name='chat_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='professional',
            name='education',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='professional',
            name='languages',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='professional',
            name='locked_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='professional',
            name='max_simultaneous_sessions',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='professional',
            name='primary_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_professionals', to='quickconnect.category'),
        ),
        migrations.AddField(
            model_name='professional',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='professional_profiles/'),
        ),
        migrations.AddField(
            model_name='professional',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='professional',
            name='total_reviews',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='professional',
            name='video_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='professional',
            name='voice_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='quickconnect.category'),
        ),
        migrations.AddField(
            model_name='session',
            name='rate_used',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='notification_preferences',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='timezone',
            field=models.CharField(default='UTC', max_length=50),
        ),
        migrations.CreateModel(
            name='ProfessionalCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(default=False)),
                ('years_experience', models.IntegerField(default=0)),
                ('certification', models.CharField(blank=True, max_length=200, null=True)),
                ('verified', models.BooleanField(default=False)),
                ('rate_override', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quickconnect.category')),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quickconnect.professional')),
            ],
            options={
                'verbose_name_plural': 'Professional Categories',
                'unique_together': {('professional', 'category')},
            },
        ),
        migrations.AddField(
            model_name='professional',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='multi_category_professionals', through='quickconnect.ProfessionalCategory', to='quickconnect.category'),
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='quickconnect.category')),
            ],
            options={
                'verbose_name_plural': 'SubCategories',
                'ordering': ['category', 'name'],
                'unique_together': {('category', 'name')},
            },
        ),
        migrations.AddField(
            model_name='professional',
            name='subcategories',
            field=models.ManyToManyField(blank=True, related_name='professionals', to='quickconnect.subcategory'),
        ),
        migrations.CreateModel(
            name='ProfessionalSpecialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quickconnect.category')),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specializations', to='quickconnect.professional')),
            ],
            options={
                'unique_together': {('professional', 'category', 'name')},
            },
        ),
    ]
