# Generated by Django 5.2.7 on 2025-11-21 03:03

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickconnect', '0002_alter_category_options_alter_professional_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='session',
            old_name='client_review',
            new_name='review',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='session',
            name='client_rating',
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='checkout_request_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='receipt_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='professional',
            name='current_workload',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='professional',
            name='last_active',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='professional',
            name='max_workload',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='professional',
            name='success_rate',
            field=models.DecimalField(decimal_places=2, default=95.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='session',
            name='mode',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='rating',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='session',
            name='urgency',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='notification_settings',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='preferences',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='sender_type',
            field=models.CharField(choices=[('client', 'Client'), ('professional', 'Professional'), ('system', 'System')], max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('session_request', 'Session Request'), ('session_accepted', 'Session Accepted'), ('session_rejected', 'Session Rejected'), ('payment_received', 'Payment Received'), ('session_reminder', 'Session Reminder'), ('system', 'System Notification'), ('call_started', 'Call Started'), ('call_ended', 'Call Ended'), ('call_quality_alert', 'Call Quality Alert'), ('professional_approved', 'Professional Approved'), ('professional_rejected', 'Professional Rejected')], max_length=25),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('card', 'Credit/Debit Card'), ('paypal', 'PayPal'), ('bank_transfer', 'Bank Transfer'), ('wallet', 'Digital Wallet'), ('mpesa', 'M-Pesa')], default='Mpesa', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='professional',
            name='avg_response_time',
            field=models.CharField(default='< 4 hours', max_length=20),
        ),
        migrations.AlterField(
            model_name='professional',
            name='rate',
            field=models.DecimalField(decimal_places=2, default=50.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='session',
            name='client_id',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.CharField(max_length=100, unique=True)),
                ('client_name', models.CharField(max_length=200)),
                ('professional_name', models.CharField(max_length=200)),
                ('service_type', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('transaction_id', models.CharField(max_length=100)),
                ('payment_method', models.CharField(max_length=50)),
                ('issue_date', models.DateField(auto_now_add=True)),
                ('issue_time', models.TimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='quickconnect.payment')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='quickconnect.session')),
            ],
            options={
                'ordering': ['-issue_date', '-issue_time'],
            },
        ),
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('category', models.CharField(choices=[('technical', 'Technical Issue'), ('billing', 'Billing/Payment'), ('session', 'Session Related'), ('account', 'Account Issue'), ('general', 'General Inquiry')], default='general', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='open', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('related_payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quickconnect.payment')),
                ('related_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quickconnect.session')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
